pipeline{

	agent any
	 
	stages{
		stage('Build'){
			steps{   
				 echo "build"
        		}  
		}
		stage('testing stage') {
		     	steps {
				echo "test"
			}
    		}
		stage('Deploy'){
			steps{
				withCredentials([[$class	:	'UsernamePasswordMultiBinding',
				credentialsId	:	'PCF_LOGIN',
				usernameVariable	:	'jadhav.prashant843@gmail.com',
				passwordVariable	:	'8983058583Pra@']]){
					sh '/user/local/bin/cf login -a http://api.run.pivotal.io -u jadhav.prashant843@gmail.com -p 8983058583Pra@'
					sh '/user/local/bin/cf push'
				} 
			}
		}
	}

}
